<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class RealisticMoviesSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [
            // 1. Phim Đang Chiếu Hot
            [
                'title' => 'Deadpool & Wolverine',
                'original_title' => 'Deadpool & Wolverine',
                'slug' => 'deadpool-and-wolverine',
                'description' => 'Sau nhiều năm ẩn mình, Wade Wilson buộc phải tái xuất giang hồ và hợp tác cùng Wolverine trong một nhiệm vụ nghẹt thở để bảo vệ dòng thời gian và vũ trụ của mình trước sự sụp đổ.',
                'director' => 'Shawn Levy',
                'cast' => ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin', 'Morena Baccarin'],
                'genre' => ['Hành Động', 'Hài Hước', 'Viễn Tưởng'],
                'duration' => 128,
                'release_date' => '2026-07-26',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/yDHYTfa2wfbyAH09VPNaqiC4qqn.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=73_1biulkYk',
                'rating' => 9.2,
                'age_rating' => 'T18',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Dune: Hành Tinh Cát - Phần Hai',
                'original_title' => 'Dune: Part Two',
                'slug' => 'dune-part-two',
                'description' => 'Paul Atreides kết hợp cùng Chani và người Fremen để tiến hành cuộc trả thù chống lại những kẻ đã hủy hoại gia tộc mình. Đứng trước sự lựa chọn giữa tình yêu và số phận của vũ trụ.',
                'director' => 'Denis Villeneuve',
                'cast' => ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem'],
                'genre' => ['Viễn Tưởng', 'Phiêu Lưu', 'Hành Động'],
                'duration' => 166,
                'release_date' => '2026-03-01',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Way9Dexny3w',
                'rating' => 9.5,
                'age_rating' => 'T16',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Spider-Man: Du Hành Vũ Trụ Nhện',
                'original_title' => 'Spider-Man: Across the Spider-Verse',
                'slug' => 'spider-man-across-the-spider-verse',
                'description' => 'Miles Morales được phóng qua Đa vũ trụ, nơi cậu chạm trán với một nhóm Người Nhện có nhiệm vụ bảo vệ sự tồn tại của nó. Nhưng khi các anh hùng xung đột về cách xử lý mối đe dọa mới, Miles phải định nghĩa lại ý nghĩa của việc trở thành một anh hùng.',
                'director' => 'Joaquim Dos Santos, Kemp Powers',
                'cast' => ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
                'genre' => ['Hoạt Hình', 'Hành Động', 'Phiêu Lưu'],
                'duration' => 140,
                'release_date' => '2026-06-02',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=cqGjhVJWtEg',
                'rating' => 9.6,
                'age_rating' => 'T13',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Những Mảnh Ghép Cảm Xúc 2',
                'original_title' => 'Inside Out 2',
                'slug' => 'inside-out-2',
                'description' => 'Chào đón sự xuất hiện của những cảm xúc mới trong tâm trí Riley khi bước vào tuổi dậy thì: Lo Âu (Anxiety), Ganh Tị (Envy), Xấu Hổ (Embarrassment) và Chán Nản (Ennui).',
                'director' => 'Kelsey Mann',
                'cast' => ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman'],
                'genre' => ['Hoạt Hình', 'Gia Đình', 'Hài Hước'],
                'duration' => 96,
                'release_date' => '2026-06-14',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=LEjhY15eCx0',
                'rating' => 9.1,
                'age_rating' => 'P',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Godzilla x Kong: Đế Chế Mới',
                'original_title' => 'Godzilla x Kong: The New Empire',
                'slug' => 'godzilla-x-kong-the-new-empire',
                'description' => 'Kong và Godzilla phải tạm gác lại mối thù truyền kiếp để liên minh chống lại một mối đe dọa khổng lồ chưa từng được khám phá ẩn sâu trong lòng Trái Đất.',
                'director' => 'Adam Wingard',
                'cast' => ['Rebecca Hall', 'Brian Tyree Henry', 'Dan Stevens'],
                'genre' => ['Hành Động', 'Viễn Tưởng', 'Phiêu Lưu'],
                'duration' => 115,
                'release_date' => '2026-03-29',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/z1p34vh7dE9xph4cziscF3YrYsP.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/qrGtww9E23KVCh8JwNm1PdxpZuz.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=lV1OOlGwExg',
                'rating' => 8.8,
                'age_rating' => 'T13',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Exhuma: Quật Mộ Trùng Ma',
                'original_title' => 'Exhuma',
                'slug' => 'exhuma-quat-mo-trung-ma',
                'description' => 'Một gia đình giàu có ở Los Angeles trải qua hàng loạt sự kiện huyền bí kỳ lạ và đã liên hệ với hai pháp sư trẻ tuổi tài năng để bảo vệ đứa con sơ sinh khỏi lời nguyền tổ tiên.',
                'director' => 'Jang Jae-hyun',
                'cast' => ['Choi Min-sik', 'Kim Go-eun', 'Yoo Hae-jin', 'Lee Do-hyun'],
                'genre' => ['Kinh Dị & Bí Ẩn', 'Tâm Lý - Chính Kịch'],
                'duration' => 134,
                'release_date' => '2026-03-15',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/kdpq2Xv2qX2ZpGeql0sK9t54C4j.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/5Eip60UDiPLASyKjmHPMruggTc4.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=0hB3v5fO40w',
                'rating' => 9.0,
                'age_rating' => 'T18',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Lật Mặt 7: Một Điều Ước',
                'original_title' => 'Face Off 7: One Wish',
                'slug' => 'lat-mat-7-mot-dieu-uoc',
                'description' => 'Câu chuyện cảm động về tình mẫu tử của bà Hai 73 tuổi sống một mình tại làng K\'Long K\'Lanh và năm người con đã trưởng thành tỏa đi khắp mọi miền đất nước.',
                'director' => 'Lý Hải',
                'cast' => ['Thanh Hiền', 'Trương Minh Cường', 'Đinh Y Nhung', 'Quách Ngọc Tuyên'],
                'genre' => ['Tâm Lý - Chính Kịch', 'Gia Đình'],
                'duration' => 138,
                'release_date' => '2026-04-26',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/wS6pZp6PzN2s9P0kE0k0t8f.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/b87x8j7P8K7x8k8f7.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=pE78iHqP2Vw',
                'rating' => 9.3,
                'age_rating' => 'T13',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Kung Fu Panda 4',
                'original_title' => 'Kung Fu Panda 4',
                'slug' => 'kung-fu-panda-4',
                'description' => 'Po được chọn trở thành Thủ lĩnh Tinh thần của Thung lũng Hòa Bình và phải tìm kiếm cũng như huấn luyện một Thần Long Đại Hiệp mới trong khi đối đầu với mụ Tắc Kè Bông xảo quyệt.',
                'director' => 'Mike Mitchell',
                'cast' => ['Jack Black', 'Awkwafina', 'Viola Davis', 'Dustin Hoffman'],
                'genre' => ['Hoạt Hình', 'Hành Động', 'Hài Hước'],
                'duration' => 94,
                'release_date' => '2026-03-08',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=_inKs4eeHiI',
                'rating' => 8.6,
                'age_rating' => 'K',
                'status' => 'now_showing',
            ],

            // 2. ✨ Phim Suất Chiếu Sớm (Sneak Show)
            [
                'title' => 'Alien: Romulus (Suất Chiếu Sớm)',
                'original_title' => 'Alien: Romulus',
                'slug' => 'alien-romulus-sneak-show',
                'description' => 'Một nhóm bạn trẻ thực dân không gian đối mặt với hình dạng sinh vật đáng sợ nhất trong vũ trụ khi dọn dẹp các mảnh vỡ của một trạm vũ trụ bị bỏ hoang.',
                'director' => 'Fede Álvarez',
                'cast' => ['Cailee Spaeny', 'David Jonsson', 'Archie Renaux'],
                'genre' => ['Kinh Dị & Bí Ẩn', 'Viễn Tưởng'],
                'duration' => 119,
                'release_date' => '2026-09-05',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/b33nnKl1GSFbao8l3Mie6YW09BP.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=x0XDEhP4MQs',
                'rating' => 9.1,
                'age_rating' => 'T18',
                'status' => 'now_showing',
            ],
            [
                'title' => 'Joker: Điên Có Đôi',
                'original_title' => 'Joker: Folie à Deux',
                'slug' => 'joker-folie-a-deux',
                'description' => 'Arthur Fleck bị giam giữ tại Arkham chờ xét xử cho những tội ác của mình dưới danh nghĩa Joker. Trong khi vật lộn với danh tính kép của mình, Arthur không chỉ tình cờ gặp được tình yêu đích thực.',
                'director' => 'Todd Phillips',
                'cast' => ['Joaquin Phoenix', 'Lady Gaga', 'Brendan Gleeson'],
                'genre' => ['Tâm Lý - Chính Kịch', 'Lãng Mạn'],
                'duration' => 138,
                'release_date' => '2026-10-04',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/aciP8Km0waTLXEYf5ybFK5CSNkM.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/uLqNGzJ32va0jR08CpjGzS3Mh4Y.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=_OKAwz2MsJs',
                'rating' => 8.9,
                'age_rating' => 'T18',
                'status' => 'now_showing',
            ],

            // 3. ⏳ Phim Sắp Chiếu (Coming Soon)
            [
                'title' => 'Avatar: Lửa Và Tro Tàn',
                'original_title' => 'Avatar: Fire and Ash',
                'slug' => 'avatar-fire-and-ash',
                'description' => 'Hành trình tiếp theo của Jake Sully và gia đình trên hành tinh Pandora, khám phá tộc người Tro Tàn (Ash People) đầy bí ẩn và hung hăng.',
                'director' => 'James Cameron',
                'cast' => ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver'],
                'genre' => ['Viễn Tưởng', 'Phiêu Lưu', 'Hành Động'],
                'duration' => 192,
                'release_date' => '2026-12-19',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/vL5LR6WdxWPjC3zU458Vq68z7q.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=d9MyW72ELq0',
                'rating' => 9.7,
                'age_rating' => 'T13',
                'status' => 'coming_soon',
            ],
            [
                'title' => 'Captain America: Thế Giới Mới Dũng Cảm',
                'original_title' => 'Captain America: Brave New World',
                'slug' => 'captain-america-brave-new-world',
                'description' => 'Sam Wilson chính thức đảm nhận trọng trách Đội trưởng Mỹ và vướng vào một âm mưu quốc tế nguy hiểm sau cuộc gặp gỡ với Tổng thống đắc cử Thaddeus Ross.',
                'director' => 'Julius Onah',
                'cast' => ['Anthony Mackie', 'Harrison Ford', 'Giancarlo Esposito'],
                'genre' => ['Hành Động', 'Viễn Tưởng', 'Phiêu Lưu'],
                'duration' => 135,
                'release_date' => '2026-02-14',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/kHQ4bHn7Pq2k2vPZ3cZq3yE5Z6G.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/9l1tOQCQYStpq7v4L4j5j8g.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=1pHDWnXmK7Y',
                'rating' => 8.7,
                'age_rating' => 'T13',
                'status' => 'coming_soon',
            ],
            [
                'title' => 'Hành Trình Của Moana 2',
                'original_title' => 'Moana 2',
                'slug' => 'moana-2',
                'description' => 'Sau khi nhận được cuộc gọi bất ngờ từ tổ tiên tìm đường của mình, Moana phải thực hiện một hành trình tới những vùng biển xa xôi nguy hiểm của Châu Đại Dương.',
                'director' => 'David G. Derrick Jr.',
                'cast' => ['Auli\'i Cravalho', 'Dwayne Johnson', 'Alan Tudyk'],
                'genre' => ['Hoạt Hình', 'Phiêu Lưu', 'Gia Đình'],
                'duration' => 100,
                'release_date' => '2026-11-27',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/m135jYF0v2v8k4pZ3cZq3yE5Z6G.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/7h65MWLXvK5c0C4v2v8k4pZ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=hDZ7y8RP5HE',
                'rating' => 9.0,
                'age_rating' => 'P',
                'status' => 'coming_soon',
            ],
            [
                'title' => 'Venom: Kèo Cuối',
                'original_title' => 'Venom: The Last Dance',
                'slug' => 'venom-the-last-dance',
                'description' => 'Eddie Brock và Venom đang phải chạy trốn. Bị săn đuổi bởi cả hai thế giới của họ và khi tấm lưới ngày càng thắt lại, bộ đôi buộc phải đưa ra một quyết định tàn khốc.',
                'director' => 'Kelly Marcel',
                'cast' => ['Tom Hardy', 'Chiwetel Ejiofor', 'Juno Temple'],
                'genre' => ['Hành Động', 'Viễn Tưởng', 'Kinh Dị & Bí Ẩn'],
                'duration' => 110,
                'release_date' => '2026-10-25',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/aos8Vh0mwe9G4qR6aWp0v2v8k.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/3V4kAsNuAD59p8qR6aWp0.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=__2bjWbetsA',
                'rating' => 8.9,
                'age_rating' => 'T16',
                'status' => 'coming_soon',
            ],
            [
                'title' => 'Võ Sĩ Giác Đấu II',
                'original_title' => 'Gladiator II',
                'slug' => 'gladiator-2',
                'description' => 'Nhiều năm sau khi chứng kiến cái chết của Maximus dưới bàn tay của chú mình, Lucius phải bước vào Đấu trường La Mã sau khi quê hương của anh bị các Hoàng đế độc tài chinh phục.',
                'director' => 'Ridley Scott',
                'cast' => ['Paul Mescal', 'Pedro Pascal', 'Denzel Washington'],
                'genre' => ['Hành Động', 'Tâm Lý - Chính Kịch', 'Phiêu Lưu'],
                'duration' => 148,
                'release_date' => '2026-11-22',
                'poster_url' => 'https://image.tmdb.org/t/p/w780/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
                'backdrop_url' => 'https://image.tmdb.org/t/p/original/euYIwmwkmz95mnXvufEmbL6ovhA.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=4rgYUipGJNo',
                'rating' => 9.4,
                'age_rating' => 'T18',
                'status' => 'coming_soon',
            ],
        ];

        foreach ($movies as $movieData) {
            Movie::updateOrCreate(
                ['slug' => $movieData['slug']],
                $movieData
            );
        }
    }
}
